### ISSUE TITLE
failed sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by idoo** [kalys/capistrano-nginx-unicorn#22]
``` ruby
DEBUG [1bd7e6bd]    sudo: нет tty и не указана программа askpass
cap aborted!
SSHKit::Command::Failed: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: sudo: нет tty и не указана программа askpass
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/command.rb:98:in `exit_status='
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:142:in `block (4 levels) in _execute'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel.rb:551:in `call'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel.rb:551:in `do_request'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:561:in `channel_request'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:205:in `process'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:169:in `block in loop'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:169:in `loop'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:169:in `loop'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:164:in `block (2 levels) in _execute'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel.rb:514:in `call'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:545:in `channel_open_confirmation'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:205:in `process'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:169:in `block in loop'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:169:in `loop'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/net-ssh-2.9.0/lib/net/ssh/connection/session.rb:169:in `loop'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:166:in `block in _execute'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:123:in `tap'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:123:in `_execute'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/capistrano-3.2.1/lib/capistrano/dsl.rb:27:in `sudo'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/capistrano-nginx-unicorn-0.1.0/lib/capistrano/tasks/nginx.rake:12:in `block (3 levels) in <top (required)>'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/doo/.rvm/gems/ruby-2.1.1@rails-foundation/gems/sshkit-1.4.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => nginx:setup
(See full trace by running task with --trace)
```

**Comment by idoo** [comment]
i think need options in config to set password

**Comment by alexagranov** [comment]
Ivan - you should be using ssh keys, not passwords.  See here for some help on how servers are usually set up for use with Capistrano - http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/

**Comment by idoo** [comment]
right, i had copy ssh key, but sudo is need user password — what wrong?

**Comment by kalys** [comment]
Add this line to your `deploy.rb` (for example after `set :application, "blog"`)

`default_run_options[:pty] = true`

Source: http://stackoverflow.com/questions/11562147/capistrano-errors

**Comment by idoo** [comment]
thx, i think need add this row to wiki :+1:

**Comment by boena** [comment]
This won't work if you have followed the guide on capistranos homepage, as I have no idea on what the password is anymore for the deploy user. Is there some other way to get this fixed?

**Comment by rockaBe** [comment]
could this issue be closed - cause it is not related to the gem itself, but the user's configuration.
