### ISSUE TITLE
Could not find rake when attempting to `unicorn:start`.

### ISSUE THREAD

**Issue by bhardin** [kalys/capistrano-nginx-unicorn#31]
``` bash
~/Code/bggtools (master ✔) ᐅ cap production unicorn:start
DEBUG[1a1279d2] Running /usr/bin/env [ -d ~/.rvm ] on 23.239.7.54
DEBUG[1a1279d2] Command: [ -d ~/.rvm ]
DEBUG[1a1279d2] Finished in 0.696 seconds with exit status 0 (successful).
DEBUG[fea6270f] Running ~/.rvm/bin/rvm version on 23.239.7.54
DEBUG[fea6270f] Command: ~/.rvm/bin/rvm version
DEBUG[fea6270f]     rvm 1.26.5 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG[fea6270f] Finished in 0.440 seconds with exit status 0 (successful).
rvm 1.26.5 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG[759fae2d] Running ~/.rvm/bin/rvm current on 23.239.7.54
DEBUG[759fae2d] Command: ~/.rvm/bin/rvm current
DEBUG[759fae2d]     ruby-2.1.5
DEBUG[759fae2d] Finished in 1.014 seconds with exit status 0 (successful).
ruby-2.1.5
DEBUG[ab1a7a30] Running ~/.rvm/bin/rvm default do ruby --version on 23.239.7.54
DEBUG[ab1a7a30] Command: ~/.rvm/bin/rvm default do ruby --version
DEBUG[ab1a7a30]     ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
DEBUG[ab1a7a30] Finished in 0.771 seconds with exit status 0 (successful).
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
INFO[d1f6b5fa] Running /usr/bin/env sudo service unicorn_bgg-tools_production start on 23.239.7.54
DEBUG[d1f6b5fa] Command: /usr/bin/env sudo service unicorn_bgg-tools_production start
DEBUG[d1f6b5fa]     /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.1.0 in any of the sources (Bundler::GemNotFound)
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:85:in `map!'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:85:in `materialize'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:114:in `specs'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:159:in `specs_for'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:148:in `requested_specs'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler/environment.rb:18:in `requested_specs'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:13:in `setup'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler.rb:120:in `setup'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:17:in `<top (required)>'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
DEBUG[d1f6b5fa]         from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
```

Any ideas what is going on? I've googled for the better part of a day, and I need some help.

**Comment by alexagranov** [comment]
Looks like you have a problem with your rvm installation.  Look at the start of the stack trace, you're picking up ruby 1.9.1, which is probably the default ruby on the box.
